<MySwiper@MDSwiperItem>

BoxLayout:
    orientation:'vertical'
    MDCard:
        size_hint:None, None
        size:600, 80
        pos_hint:{"center_x": 0.5, "center_y":0}
        elevation:10
        padding:20
        spacing:15
        orientation:'horizontal'
            
        Button:
            text:"Notify"
            background_normal:''
            background_color:(0,1,0,0.5)
            
        Button:
            text:"Rewords"
            background_normal:''
            background_color:(0,0.5,1,0.5)
            
        Button:
            text:"Mail"
            background_normal:''
            background_color:(1,0,0,0.5)
            
        Button:
            text:"Chat"
            background_normal:''
            background_color:(0.5,0,1,0.5)
            
        Button:
            text:"Pay"
            background_normal:''
            background_color:(1,0,0,0.5)
            
        Button:
            text:"Search"
            background_normal:''
            background_color:(0,0,0,0.5)
                
        Button:
            text:"Games"
            background_normal:''
            color:(0,0,0,1)
            background_color:(1,1,0,0.5) 
        

    Screen:
        MDCard:
            size_hint:None, None
            size:500, 400
            pos_hint:{"center_x": 0.5, "center_y":0.5}
            elevation:10
            padding:25
            spacing:25
            orientation:'vertical'      
            MDLabel:
                id: welcome_label
                text:"WELCOME"   
                font_size:40
                halign:'center'
                size_hint_y:None
                height:self.texture_size[1]
                padding_y:15

            MDTextFieldRound:
                id:user
                hint_text:"username"
                icon_right:"account"
                size_hint_x:None
                width:200
                font_size:18
                pos_hint:{"center_x":0.5} 

            MDTextFieldRound:
                id:password
                hint_text:"password"
                icon_right:"eye-off"
                size_hint_x:None
                width:200
                font_size:18
                pos_hint:{"center_x":0.5}
                password:True

            MDRoundFlatButton:
                text:"LOG IN"
                font_size:12
                pos_hint:{"center_x":0.5}
                on_press: app.verify()

            MDRoundFlatButton:
                text:"CLEAR"
                font_size:12
                pos_hint:{"center_x":0.5}
                on_press: app.clear()
            Widget:
                size_hint_y: None
                height:10


        
    MDCard:
        size_hint:None, None
        size:600, 80 
        pos_hint:{"center_x": 0.5, "center_y":0}
        BoxLayout:
            orientation:"horizontal"
            padding:15
            spacing:15
            Image:
                source:'images/home.png'
            Image:
                source:'images/sunrise.png'
            Image:
                source:'images/shopping.png'
            Image:
                source:'images/dollar.jfif'
            Image:
                source:'images/telephone.png'
            Image:
                source:'images/Earth.ico'
            Image:
                source:'images/help.jfif'                        



